# arguments for dataset
dataset: potsdam
nclass: 6
crop_size: 513
data_root: ./potsdam

# arguments for training
epochs: 150
batch_size: 2 # per GPU x 4 GPUs
lr: 0.001
lr_multi: 10.0

criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
# criterion:
#   name: OHEM
#   kwargs:
#     ignore_index: 255
#     thresh: 0.7
#     min_kept: 200000

criterion_u:
  name: CELoss
  kwargs:
    ignore_index: 255

# arguments for model
model:
  backbone:
    type: model.backbone.mit.mit_b5
    kwargs:
      embed_dims: [64, 128, 320, 512]
      pretrained: True
  decoder:
    type: model.semseg.allspark.SemiDecoder
    kwargs:
      num_heads: 2
      num_class: 6
      in_planes: [64, 128, 320, 512]
      image_size: 513
      warmup_epoch: 5
      embedding_dim: 768
